const blogs = require('./blogs_enriched.json');

function cleanBlogContent(content) {
  let cleaned = content;

  // Remove header artifacts at the start
  cleaned = cleaned.replace(/^(GPT Church - Hebron City\n|Sunday,|Wednesday,|Monday,|Tuesday,|Thursday,|Friday,|Saturday,|Sermon by|TITLE:|Teaching by|Teaching_GPT Church - Hebron City_|#GrowingInChristlikeness\n?)+/gi, '');
  
  // Fix date patterns first
  cleaned = cleaned.replace(/([A-Z][a-z]+)(\d{1,2},)/g, '$1 $2');
  cleaned = cleaned.replace(/([A-Z][a-z]+)(\d{1,2})(\d{4})/g, '$1 $2, $3');
  
  // Fix >> markers - replace with bullet points
  cleaned = cleaned.replace(/>>/g, '\n\n>> ');
  
  // Insert space between lowercase and uppercase (camelCase) - multiple passes
  cleaned = cleaned.replace(/([a-z])([A-Z])/g, '$1 $2');
  cleaned = cleaned.replace(/([a-z])([A-Z])/g, '$1 $2');
  cleaned = cleaned.replace(/([a-z])([A-Z])/g, '$1 $2');
  
  // Common word replacements - add spaces between merged words
  const replacements = [
    [/Akingdommindset/gi, 'A kingdom mindset'],
    [/Worldlymindset/gi, 'worldly mindset'],
    [/Problemsthataffect/gi, 'Problems that affect'],
    [/Gehaziwanted/gi, 'Gehazi wanted'],
    [/MayGodgiveus/gi, 'May God give us'],
    [/TheLordtold/gi, 'The Lord told'],
    [/Thesonsin/gi, 'The sons in'],
    [/Yourwomb/gi, 'Your womb'],
    [/Wilbecome/gi, 'will become'],
    [/Fromthevery/gi, 'From the very'],
    [/Onenation/gi, 'One nation'],
    [/Yourolderson/gi, 'your older son'],
    [/Younger son/g, 'younger son'],
    [/Allright/gi, 'All right'],
    [/Jacob replied/gi, 'Jacob replied'],
    [/Buttrade/gi, 'but trade'],
    [/Yourfirstbornson/gi, 'your firstborn son'],
    [/Whatgoodismy/gi, 'What good is my'],
    [/ThenJacob/gi, 'Then Jacob'],
    [/Esau some/gi, 'Esau some'],
    [/Breadand/gi, 'Bread and'],
    [/Lentilstew/gi, 'lentil stew'],
    [/Esau ate/gi, 'Esau ate'],
    [/Gotup/gi, 'got up'],
    [/Showedcontempt/gi, 'showed contempt'],
    [/Firstbornson/gi, 'firstborn son'],
    [/Putofftheold/gi, 'put off the old'],
    [/Putonthelew/gi, 'put on the new'],
    [/Twomannerofpeople/gi, 'Two manner of people'],
    [/Twocities/gi, 'two cities'],
    [/Twosystems/gi, 'two systems'],
    [/Apatternwe/gi, 'A pattern we'],
    [/Theworldsystem/gi, 'The world system'],
    [/Versusthe/gi, 'versus the'],
    [/Kingdommindset/gi, 'kingdom mindset'],
    [/Lastweek/gi, 'Last week'],
    [/Jacoband/gi, 'Jacob and'],
    [/Representstheflesh/gi, 'represents the flesh'],
    [/Representsthespirit/gi, 'represents the spirit'],
    [/Godvalued/gi, 'God valued'],
    [/Throughbirthright/gi, 'Through birthright'],
    [/Godwas/gi, 'God was'],
    [/Thelineage/gi, 'the lineage'],
    [/Wouldlead/gi, 'would lead'],
    [/Worldlyor/gi, 'worldly or'],
    [/Manifestwhat/gi, 'manifest what'],
    [/Youvalue/gi, 'You value'],
    [/Representsthose/gi, 'represents those'],
    [/Despisewhat/gi, 'despise what'],
    [/Godvalues/gi, 'God values'],
    [/Whengoverned/gi, 'When governed'],
    [/Fleshtend/gi, 'flesh tend'],
    [/Toexaggerate/gi, 'to exaggerate'],
    [/Saidhewas/gi, 'said he was'],
    [/Abouttodie/gi, 'about to die'],
    [/Willall/gi, 'will all'],
    [/Facechallenges/gi, 'face challenges'],
    [/Problemsandtrials/gi, 'problems and trials'],
    [/Bornagainornot/gi, 'born again or not'],
    [/Ourresponse/gi, 'Our response'],
    [/Revealswhether/gi, 'reveals whether'],
    [/Governedbythe/gi, 'governed by the'],
    [/Problemlooks/gi, 'problem looks'],
    [/Biggerthan/gi, 'bigger than'],
    [/Youwillbe/gi, 'You will be'],
    [/Afraidof/gi, 'afraid of'],
    [/ThePhilistines/gi, 'the Philistines'],
    [/Theenemy/gi, 'the enemy'],
    [/Butwhen/gi, 'But when'],
    [/Kingdomperspective/gi, 'kingdom perspective'],
    [/Youplacethem/gi, 'You place them'],
    [/Wherethey/gi, 'where they'],
    [/Seewith/gi, 'see with'],
    [/Godseye/gi, "God's eye"],
    [/PerspectiveThelarge/gi, 'perspective. The large'],
    [/Problemsfrom/gi, 'problems from'],
    [/Fadeand/gi, 'fade and'],
    [/Becomessmall/gi, 'becomes small'],
    [/Ifyouhave/gi, 'If you have'],
    [/Faithas/gi, 'faith as'],
    [/Smallas/gi, 'small as'],
    [/Themustardseed/gi, 'the mustard seed'],
    [/Youcansay/gi, 'you can say'],
    [/Theentrylevel/gi, 'the entry level'],
    [/FaithThatmoves/gi, 'Faith. That moves'],
    [/MountainsFaiththat/gi, 'mountains. Faith that'],
    [/Godgivesyou/gi, 'God gives you'],
    [/Whenyouget/gi, 'when you get'],
    [/Mountainmoving/gi, 'mountain moving'],
    [/Youwillsee/gi, 'You will see'],
    [/Themountain/gi, 'the mountain'],
    [/DifferentlyWhat/gi, 'differently. What'],
    [/Greatfaith/gi, 'great faith'],
    [/CapacityIf/gi, 'capacity. If'],
    [/Mountaincan/gi, 'mountain can'],
    [/Jesusrebuked/gi, 'Jesus rebuked'],
    [/Thedisciples/gi, 'the disciples'],
    [/Werecaught/gi, 'were caught'],
    [/Inastorm/gi, 'in a storm'],
    [/Wereafraid/gi, 'were afraid'],
    [/Littlefaith/gi, 'little faith'],
    [/Jesusresponded/gi, 'Jesus responded'],
    [/Havesolittle/gi, 'have so little'],
    [/FaithThen/gi, 'faith. Then'],
    [/Andrebuked/gi, 'and rebuked'],
    [/Andsuddenly/gi, 'and suddenly'],
    [/Therewas/gi, 'there was'],
    [/Agreatcalm/gi, 'a great calm'],
    [/Jesuswas/gi, 'Jesus was'],
    [/Expectingthem/gi, 'expecting them'],
    [/Withtheir/gi, 'with their'],
    [/Faithto/gi, 'faith to'],
    [/Rebukethe/gi, 'rebuke the'],
    [/ProblemWhy/gi, 'problem. Why'],
    [/Rebukesomeone/gi, 'rebuke someone'],
    [/Givencapacity/gi, 'given capacity'],
    [/ExaggeratesThings/gi, 'exaggerates things.'],
    [/Yourespond/gi, 'You respond'],
    [/Differentlyfrom/gi, 'differently from'],
    [/Godsperspective/gi, "God's perspective"],
    [/Esaulosthis/gi, 'Esau lost his'],
    [/Becausehe/gi, 'because he'],
    [/Didntvalue/gi, "didn't value"],
    [/Jacobvalued/gi, 'Jacob valued'],
    [/Honoredby/gi, 'honored by'],
    [/Esauwas/gi, 'Esau was'],
    [/Askilled/gi, 'a skilled'],
    [/Waswild/gi, 'was wild'],
    [/Undomesticated/gi, 'undomesticated'],
    [/Unbrokenand/gi, 'unbroken and'],
    [/Aperson/gi, 'A person'],
    [/Governedby/gi, 'governed by'],
    [/Thespirithave/gi, 'the spirit have'],
    [/Abrokenheart/gi, 'a broken heart'],
    [/Andacontrite/gi, 'and a contrite'],
    [/Systemisunbroken/gi, 'system is unbroken'],
    [/Tenderin/gi, 'tender in'],
    [/Theirspirit/gi, 'their spirit'],
    [/Theycannot/gi, 'They cannot'],
    [/Becorrected/gi, 'be corrected'],
    [/Makesurethat/gi, 'Make sure that'],
    [/Nooneis/gi, 'no one is'],
    [/Immoralor/gi, 'immoral or'],
    [/Godlesslike/gi, 'godless like'],
    [/Esauwho/gi, 'Esau who'],
    [/Tradedhis/gi, 'traded his'],
    [/Firstbornson/gi, 'firstborn son'],
    [/Forasingle/gi, 'for a single'],
    [/Youknowthat/gi, 'You know that'],
    [/Afterward/gi, 'afterward'],
    [/Wantedhis/gi, 'wanted his'],
    [/Fathersblessing/gi, "father's blessing"],
    [/Wasrejected/gi, 'was rejected'],
    [/Itwastoolate/gi, 'It was too late'],
    [/Forrepentance/gi, 'for repentance'],
    [/Eventhough/gi, 'even though'],
    [/Hewith/gi, 'he with'],
    [/Bittertears/gi, 'bitter tears'],
    [/Prioritizedworldlythings/gi, 'Prioritized worldly things'],
    [/Overwhat/gi, 'over what'],
    [/Amorselof/gi, 'A morsel of'],
    [/Foodor/gi, 'food or'],
    [/Soupis/gi, 'soup is'],
    [/Godwasnt/gi, "God wasn't"],
    [/Heneeded/gi, 'He needed'],
    [/Towaitfor/gi, 'to wait for'],
    [/Therighttime/gi, 'the right time'],
    [/Heneedednot/gi, 'He needed not'],
    [/Toexchangeit/gi, 'to exchange it'],
    [/Thesametemptation/gi, 'The same temptation'],
    [/Cameto/gi, 'came to'],
    [/Turnstones/gi, 'turn stones'],
    [/Intobread/gi, 'into bread'],
    [/Atemptation/gi, 'A temptation'],
    [/Thatwe/gi, 'that we'],
    [/Willfallfor/gi, 'will fall for'],
    [/Ifweare/gi, 'if we are'],
    [/Weareunable/gi, 'We are unable'],
    [/Godstiming/gi, "God's timing"],
    [/Godof/gi, 'God of'],
    [/AbrahamIsaac/gi, 'Abraham, Isaac'],
    [/AndJacob/gi, 'and Jacob'],
    [/Insteadof/gi, 'Instead of'],
    [/Esaumissedit/gi, 'Esau missed it'],
    [/Forallowing/gi, 'for allowing'],
    [/Himselftobe/gi, 'himself to be'],
    [/Hisappetite/gi, 'his appetite'],
    [/Andhisimpulses/gi, 'and his impulses'],
    [/Thisremindsus/gi, 'This reminds us'],
    [/Howimportantitis/gi, 'how important it is'],
    [/Forusnotto/gi, 'for us not to'],
    [/Godisgracious/gi, 'God is gracious'],
    [/Heidentifies/gi, 'He identifies'],
    [/Himselfwith/gi, 'himself with'],
    [/Adeceiver/gi, 'a deceiver'],
    [/Andsomeonewho/gi, 'and someone who'],
    [/Ismessedup/gi, 'is messed up'],
    [/NotIsrael/gi, 'Not Israel'],
    [/ButJacob/gi, 'but Jacob'],
    [/Hechanges/gi, 'He changes'],
    [/Thatwhich/gi, 'that which'],
    [/Thatperson/gi, 'that person'],
    [/Ifyouare/gi, 'If you are'],
    [/Hungryand/gi, 'hungry and'],
    [/Thirstyfor/gi, 'thirsty for'],
    [/Youareacandidate/gi, 'you are a candidate'],
    [/ForHimtodeal/gi, 'for Him to deal'],
    [/Withyouand/gi, 'with you and'],
    [/Changeyour/gi, 'change your'],
    [/Jacobaman/gi, 'Jacob, a man'],
    [/Whomessedup/gi, 'who messed up'],
    [/Manytimes/gi, 'many times'],
    [/Withakingdom/gi, 'With a kingdom'],
    [/Perspectiveyou/gi, 'perspective, you'],
    [/Ruthand/gi, 'Ruth and'],
    [/Theyareboth/gi, 'They are both'],
    [/MoabitesRuthfinds/gi, 'Moabites. Ruth finds'],
    [/Herwayintothe/gi, 'her way into the'],
    [/Lineageof/gi, 'lineage of'],
    [/Christthougha/gi, 'Christ, though a'],
    [/Shebecamea/gi, 'She became a'],
    [/Greatgreatgrandmother/gi, 'great-grandmother'],
    [/Becauseofsomething/gi, 'Because of something'],
    [/ShesaidanddidItindicated/gi, 'she said and did. It indicated'],
    [/Whereshe/gi, 'where she'],
    [/Placedher/gi, 'placed her'],
    [/ValueElimelech/gi, 'value. Elimelech'],
    [/WenttoMoab/gi, 'went to Moab'],
    [/Becauseoffamine/gi, 'because of famine'],
    [/Famineskept/gi, 'famines kept'],
    [/Comingandgoing/gi, 'coming and going'],
    [/Thenaturalrealm/gi, 'the natural realm'],
    [/Alotofshifts/gi, 'a lot of shifts'],
    [/Happeningin/gi, 'happening in'],
    [/Thetoughtimes/gi, 'the tough times'],
    [/Sametone/gi, 'same to'],
    [/Takecareof/gi, 'Take care of'],
    [/Whichdirection/gi, 'which direction'],
    [/Duringfamine/gi, 'during famine'],
    [/Troublepain/gi, 'trouble, pain'],
    [/Andproblems/gi, 'and problems'],
    [/Thedecisions/gi, 'The decisions'],
    [/Youmakein/gi, 'you make in'],
    [/Thatseason/gi, 'that season'],
    [/Canmakeor/gi, 'can make or'],
    [/Breakyou/gi, 'break you'],
    [/Itsnotthe/gi, "It's not the"],
    [/Faminethat/gi, 'famine that'],
    [/Istheproblem/gi, 'is the problem'],
    [/Butthechoices/gi, 'but the choices'],
    [/MakeAkingdom/gi, 'make. A kingdom'],
    [/Isaacwantedto/gi, 'Isaac wanted to'],
    [/GotoEgypt/gi, 'go to Egypt'],
    [/When therewas/gi, 'when there was'],
    [/Justlikehisfather/gi, 'just like his father'],
    [/Godtoldhim/gi, 'God told him'],
    [/TostayWe/gi, 'to stay. We'],
    [/Shouldnotmake/gi, 'should not make'],
    [/Basedonthephysical/gi, 'based on the physical'],
    [/Butonwhat/gi, 'but on what'],
    [/Godissing/gi, 'God is saying'],
    [/Decisionsonwhat/gi, 'decisions on what'],
    [/Everyoneelsewas/gi, 'Everyone else was'],
    [/LeavingBut/gi, 'leaving. But'],
    [/Wantedhimtostay/gi, 'wanted him to stay'],
    [/Hebeganto/gi, 'He began to'],
    [/Prosperandbecome/gi, 'prosper and become'],
    [/ProsperousHe/gi, 'prosperous. He'],
    [/Stayedinanenvironment/gi, 'stayed in an environment'],
    [/Where everyonewas/gi, 'where everyone was'],
    [/FleeingAbrahamwent/gi, 'fleeing. Abraham went'],
    [/Andthatlanded/gi, 'and that landed'],
    [/Himintrouble/gi, 'him in trouble'],
    [/Dontchange/gi, "Don't change"],
    [/Yourtheology/gi, 'your theology'],
    [/Becauseofwhat/gi, 'because of what'],
    [/Youaregoing/gi, 'you are going'],
    [/Throughtobegin/gi, 'through to begin'],
    [/Tointerpret/gi, 'to interpret'],
    [/ScripturesDifferently/gi, 'scriptures differently'],
    [/GodremainsGod/gi, 'God remains God'],
    [/Despitewhat/gi, 'despite what'],
    [/Iamgoing/gi, 'I am going'],
    [/ThroughGodconfronted/gi, 'through. God confronted'],
    [/Jobifyouare/gi, 'Job, if you are'],
    [/Amananswer/gi, 'a man, answer'],
    [/Wherewereyou/gi, 'Where were you'],
    [/Ispreadthe/gi, 'I spread the'],
    [/Cloudsandoceans/gi, 'clouds and oceans'],
    [/Godissaying/gi, 'God is saying'],
    [/Becauseofthethings/gi, 'because of the things'],
    [/Youaregoingthrough/gi, 'you are going through'],
    [/Changingyour/gi, 'changing your'],
    [/TheologyElijah/gi, 'theology. Elijah'],
    [/Comingfroma/gi, 'coming from a'],
    [/Placeofvictory/gi, 'place of victory'],
    [/Heis/gi, 'He is'],
    [/Threatenedby/gi, 'threatened by'],
    [/Jezebelandruns/gi, 'Jezebel and runs'],
    [/ProphetsofBaal/gi, 'prophets of Baal'],
    [/Killedandall/gi, 'killed and all'],
    [/Idolworshipdestroyed/gi, 'idol worship destroyed'],
    [/Herunsfroma/gi, 'He runs from a'],
    [/ThreatIf/gi, 'threat. If'],
    [/Amanwho/gi, 'A man who'],
    [/Hasbrought/gi, 'has brought'],
    [/Victoryisrunning/gi, 'victory is running'],
    [/Itimplies/gi, 'it implies'],
    [/Jezebelis/gi, 'Jezebel is'],
    [/Morepowerfulthan/gi, 'more powerful than'],
    [/Thisman/gi, 'this man'],
    [/Itwasspreading/gi, 'It was spreading'],
    [/Fearinthecampoffear/gi, 'fear in the camp of fear'],
    [/Goddidntpanic/gi, "God didn't panic"],
    [/Elijahsays/gi, 'Elijah says'],
    [/Iamtheonlyone/gi, 'I am the only one'],
    [/Lefttheyhave/gi, 'left, they have'],
    [/Killedallothers/gi, 'killed all others'],
    [/HeaskedGod/gi, 'He asked God'],
    [/Tokillhim/gi, 'to kill him'],
    [/Hetellshim/gi, 'He tells him'],
    [/Iwantyouto/gi, 'I want you to'],
    [/Gotothebrook/gi, 'go to the brook'],
    [/StaythereFor/gi, 'stay there. For'],
    [/Three months/gi, 'three months'],
    [/GodfeedsElijah/gi, 'God feeds Elijah'],
    [/Sayingnothing/gi, 'saying nothing'],
    [/ByravensEating/gi, 'by ravens. Eating'],
    [/AndrestingThree/gi, 'and resting. Three'],
    [/Months laterGod/gi, 'months later, God'],
    [/Tellshimthat/gi, 'tells him that'],
    [/Hehas/gi, 'He has'],
    [/Morethathavent/gi, 'more that haven\'t'],
    [/Bowdtoidols/gi, 'bowed to idols'],
    [/Heaskedhim/gi, 'He asked him'],
    [/Toanoint/gi, 'to anoint'],
    [/Hisjobwas/gi, 'His job was'],
    [/DoneGoand/gi, 'done. Go and'],
    [/AnointSomeoneElse/gi, 'anoint someone else.'],
    [/Dontchange/gi, "Don't change"],
    [/Whenyouare/gi, 'When you are'],
    [/Inthetrial/gi, 'in the trial'],
    [/HeisGodBefore/gi, 'He is God. Before'],
    [/AndafterHe/gi, 'and after, He'],
    [/RemainsGodSame/gi: 'remains God. Same'],
    [/Yesterdaytoday/gi, 'yesterday, today'],
    [/AndforeverHe/gi, 'and forever. He'],
    [/Hasntchanged/gi, "hasn't changed"],
    [/Hislove/gi, 'His love'],
    [/Faithfulnesspromise/gi, 'faithfulness, promise'],
    [/Andcommitment/gi, 'and commitment'],
    [/To youElimelech/gi, 'to you. Elimelech'],
    [/WenttoMoab/gi, 'went to Moab'],
    [/Becauseoffamine/gi, 'because of famine'],
    [/Hecanprovide/gi, 'He can provide'],
    [/Inyoursituation/gi, 'in your situation'],
    [/Rightwhereyouare/gi, 'right where you are'],
    [/Samaria therewas/gi, 'Samaria, there was'],
    [/Famineinthe/gi, 'famine in the'],
    [/Landtothe/gi, 'land, to the'],
    [/Extentof/gi, 'extent of'],
    [/Exchangingbabies/gi, 'exchanging babies'],
    [/ForfoodA/gi, 'for food. A'],
    [/Propheticword/gi, 'prophetic word'],
    [/Cameand/gi, 'came and'],
    [/Therewasplenty/gi, 'there was plenty'],
    [/In24hours/gi, 'in 24 hours'],
    [/Aplacethat/gi, 'a place that'],
    [/Haddespaired/gi, 'had despaired'],
    [/Maintainakingdom/gi, 'Maintain a kingdom'],
    [/PerspectiveDontget/gi: 'perspective. Don\'t get'],
    [/Influencedby/gi, 'influenced by'],
    [/Whatis/gi, 'what is'],
    [/Happeningaround/gi, 'happening around'],
    [/Lookatwhat/gi, 'Look at what'],
    [/Ishappening/gi, 'is happening'],
    [/Aroundyouand/gi, 'around you and'],
    [/Problemsfroma/gi, 'problems from a'],
    [/Kingdomperspective/gi, 'kingdom perspective'],
    [/Moabmeansfather/gi, 'Moab means father'],
    [/Apictureof/gi, 'A picture of'],
    [/Someseeking/gi, 'some seeking'],
    [/Autonomyfromthe/gi, 'autonomy from the'],
    [/FatherCutting/gi: 'father. Cutting'],
    [/Offyourself/gi, 'off yourself'],
    [/Fromyour/gi, 'from your'],
    [/SupplyGodis/gi: 'supply. God is'],
    [/OursourceWe/gi: 'our source. We'],
    [/Cant exist/gi, "can't exist"],
    [/Without HimIn/gi: 'without Him. In'],
    [/MoabElimelech/gi: 'Moab. Elimelech'],
    [/DiesHis/gi, 'dies. His'],
    [/Sonsget/gi, 'sons get'],
    [/MarriedThey/gi: 'married. They'],
    [/TodieTargeting/gi: 'die. Targeting'],
    [/Theguys/gi, 'the guys'],
    [/Whocarry/gi, 'who carry'],
    [/The seedTargeting/gi: 'the seed. Targeting'],
    [/Yourability/gi, 'your ability'],
    [/Tobe fruitful/gi, 'to be fruitful'],
    [/AndproductiveYour/gi: 'and productive. Your'],
    [/Independencefrom/gi, 'Independence from'],
    [/Godcuts/gi, 'God cuts'],
    [/Yourabilityto/gi, 'your ability to'],
    [/Be fruitful/gi, 'be fruitful'],
    [/RuthandOrpah/gi, 'Ruth and Orpah'],
    [/Weremarried/gi, 'were married'],
    [/Intothis/gi, 'into this'],
    [/FamilyThey/gi: 'family. They'],
    [/Remainedwith/gi, 'remained with'],
    [/Their motherinlaw/gi, 'their mother-in-law'],
    [/NaomiNaomi/gi, 'Naomi. Naomi'],
    [/Decides togo/gi, 'decides to go'],
    [/BackhomeBut/gi: 'back home. But'],
    [/Ruthreplied/gi, 'Ruth replied'],
    [/Dontaskme/gi, "Don't ask me"],
    [/Toleave/gi, 'to leave'],
    [/Youandturn/gi, 'you and turn'],
    [/BackWherever/gi, 'back. Wherever'],
    [/You goI/gi, 'you go, I'],
    [/WillgoWherever/gi: 'will go. Wherever'],
    [/You liveI/gi, 'you live, I'],
    [/Will liveYour/gi: 'will live. Your'],
    [/Peoplewillbe/gi, 'people will be'],
    [/My people/gi, 'my people'],
    [/AndyourGod/gi, 'and your God'],
    [/Willbemy/gi, 'will be my'],
    [/GodWherever/gi: 'God. Wherever'],
    [/You dieI/gi, 'you die, I'],
    [/Will dieand/gi: 'will die, and'],
    [/ThereIwill/gi, 'there I will'],
    [/Be buriedMay/gi: 'be buried. May'],
    [/TheLord/gi, 'the Lord'],
    [/Punishmeseverely/gi, 'punish me severely'],
    [/IfIallow/gi, 'if I allow'],
    [/Anythingbut/gi, 'anything but'],
    [/Death toseparate/gi, 'death to separate'],
    [/UsRuthwas/gi: 'us. Ruth was'],
    [/Makinga/gi, 'making a'],
    [/Commitmentto/gi, 'commitment to'],
    [/Uprootherself/gi, 'uproot herself'],
    [/Fromher/gi, 'from her'],
    [/Environmentand/gi, 'environment and'],
    [/Gotoa/gi, 'go to a'],
    [/Differentland/gi, 'different land'],
    [/Wherethey/gi, 'where they'],
    [/Arenotgood/gi, 'are not good'],
    [/Friendswith/gi, 'friends with'],
    [/Whereshewas/gi, 'where she was'],
    [/ComingfromSecondly/gi: 'coming from. Secondly'],
    [/Naomi went/gi, 'Naomi went'],
    [/Outwithmuch/gi, 'out with much'],
    [/Andwasreturning/gi, 'and was returning'],
    [/WithnothingShe/gi: 'with nothing. She'],
    [/Wasntfollowing/gi, "wasn't following"],
    [/Her because/gi, 'her because'],
    [/Lifewas/gi, 'life was'],
    [/BetteratNaomi/gi: "better at Naomi's"],
    [/HomeThereis/gi: "home. There is"],
    [/No land/gi, 'No land'],
    [/Moneyor/gi, 'money or'],
    [/WealthAll/gi: 'wealth. All'],
    [/Naomi hadwas/gi: "Naomi's had was"],
    [/GodWhere/gi: 'God. Where'],
    [/YougoI/gi, 'you go, I'],
    [/WillgoOrpah/gi: 'will go. Orpah'],
    [/LooksatNaomi/gi, 'looks at Naomi'],
    [/Andevaluates/gi, 'and evaluates'],
    [/Hercircumstances/gi, 'her circumstances'],
    [/Basedonwhat/gi, 'based on what'],
    [/Shesees/gi, 'she sees'],
    [/AndknowsShe/gi: 'and knows. She'],
    [/Wouldrather/gi, 'would rather'],
    [/DieinMoab/gi, 'die in Moab'],
    [/ThanfollowRuth/gi, 'than follow Ruth'],
    [/Sayingbetter/gi, 'Saying, better'],
    [/ThedevilI/gi, 'the devil I'],
    [/Knowthat/gi, 'know that'],
    [/TheplaceGod/gi: 'the place God'],
    [/Istellingme/gi, 'is telling me'],
    [/TogoStaying/gi: 'to go. Staying'],
    [/Inthecomfort/gi, 'in the comfort'],
    [/Ruthmade/gi, 'Ruth made'],
    [/Thechoice/gi, 'the choice'],
    [/TofollowNaomi/gi, 'to follow Naomi'],
    [/Intoanunknown/gi, 'into an unknown'],
    [/Futureandterritory/gi, 'future and territory'],
    [/Ruthrepresents/gi, 'Ruth represents'],
    [/Akingdomwhile/gi, 'a kingdom while'],
    [/Orpahrepresents/gi, 'Orpah represents'],
    [/Aworldly/gi, 'a worldly'],
    [/MindsetA/gi, 'mindset. A'],
    [/Kingdommindset/gi, 'kingdom mindset'],
    [/FollowsGodnot/gi, 'follows God not'],
    [/Becauseofthe/gi, 'because of the'],
    [/Benefitsthat/gi, 'benefits that'],
    [/Youaregoing/gi, 'you are going'],
    [/TogetNot/gi: 'to get. Not'],
    [/Forbreador/gi, 'for bread or'],
    [/ProsperityFollowing/gi: 'prosperity. Following'],
    [/Godbecause/gi, 'God because'],
    [/Ofconviction/gi, 'of conviction'],
    [/Theriskwas/gi, 'The risk was'],
    [/Ruthgetting/gi, 'Ruth getting'],
    [/Intoanenvironment/gi, 'into an environment'],
    [/Whereshecould/gi, 'where she could'],
    [/Haveexperienced/gi, 'have experienced'],
    [/HostilityA/gi, 'hostility. A'],
    [/Moabitein/gi, 'Moabite in'],
    [/IsraelHerlevel/gi: "Israel. Her level"],
    [/Ofcommitment/gi, 'of commitment'],
    [/Towhereyou/gi, 'to where you'],
    [/GoIWont/gi: 'go, I won\'t'],
    [/LeaveElijahBefore/gi: 'leave Elijah. Before'],
    [/Elisha therewere/gi, 'Elisha there were'],
    [/Prophetsbeing/gi, 'prophets being'],
    [/Mentoredby/gi, 'mentored by'],
    [/ElijahHehad/gi: 'Elijah. He had'],
    [/Aschoolof/gi, 'a school of'],
    [/Prophetswhile/gi, 'prophets while'],
    [/Elishawas/gi, 'Elisha was'],
    [/Takingcare/gi, 'taking care'],
    [/Ofhisfarm/gi, 'of his farm'],
    [/With oxen/gi, 'with oxen'],
    [/Unlike the/gi, 'Unlike the'],
    [/Schoolof/gi, 'School of'],
    [/ProphetsElisha/gi, 'prophets, Elisha'],
    [/FollowedElijah/gi, 'followed Elijah'],
    [/SayingIWont/gi: 'saying, I won\'t'],
    [/Let yougo/gi, 'let you go'],
    [/Thatwas/gi, 'That was'],
    [/CommitmentThe/gi: 'commitment. The'],
    [/Schoolofprophet/gi, 'School of prophet'],
    [/Wassomentored/gi, 'was so mentored'],
    [/That theywere/gi, 'that they were'],
    [/Accuratein/gi, 'accurate in'],
    [/Theirprophecy/gi, 'their prophecy'],
    [/Theyknewthat/gi, 'They knew that'],
    [/Elijahwould/gi, 'Elijah would'],
    [/Betakenaway/gi, 'be taken away'],
    [/But werenot/gi, 'but were not'],
    [/BotheredThey/gi: 'bothered. They'],
    [/TellElisha/gi, 'tell Elisha'],
    [/Dontyou/gi, "Don't you"],
    [/KnowthatElijah/gi, 'know that Elijah'],
    [/Isgoingtobe/gi, 'is going to be'],
    [/TakenawayThey/gi: 'taken away. They'],
    [/Misseditbecause/gi, 'missed it because'],
    [/Of theirlack/gi, 'of their lack'],
    [/Ofcommitment/gi, 'of commitment'],
    [/Yettheywere/gi, 'yet they were'],
    [/Accurateprophetically/gi, 'accurate prophetically'],
    [/They stood/gi, 'They stood'],
    [/Andwatched/gi, 'and watched'],
    [/ElijahandElisha/gi, 'Elijah and Elisha'],
    [/Across the/gi, 'across the'],
    [/RiverJordanThey/gi: 'River Jordan. They'],
    [/Didntfeel/gi, "didn't feel"],
    [/Theneedtobe/gi, 'the need to be'],
    [/Partof/gi, 'part of'],
    [/Themoveof/gi, 'the move of'],
    [/GodMichal/gi: "God. Michal"],
    [/Davidswife/gi, "David's wife"],
    [/Sawthetabernacle/gi, 'saw the tabernacle'],
    [/ComingShewas/gi: 'coming. She was'],
    [/Lookingthrough/gi, 'looking through'],
    [/Thewindownot/gi, 'the window, not'],
    [/Wantingtobe/gi, 'wanting to be'],
    [/Partofthe/gi, 'part of the'],
    [/CelebrationBeing/gi: 'celebration. Being'],
    [/Governedbythe/gi, 'governed by the'],
    [/Worldyou/gi, 'world, you'],
    [/Willseeitbut/gi, 'will see it, but'],
    [/Areunmoved/gi, 'are unmoved'],
    [/Andnothingis/gi, 'and nothing is'],
    [/Changinginyou/gi, 'changing in you'],
    [/Elishagets/gi, 'Elisha gets'],
    [/Thedouble/gi, 'the double'],
    [/Portionof/gi, 'portion of'],
    [/Elijahs/gi, "Elijah's"],
    [/AnointingOrpah/gi: 'anointing. Orpah'],
    [/Stays behind/gi, 'stays behind'],
    [/Ruthgoes/gi, 'Ruth goes'],
    [/WithNaomi/gi, 'with Naomi'],
    [/Andbecomes/gi, 'and becomes'],
    [/PartofChrists/gi: "part of Christ's"],
    [/LineageGod/gi: 'lineage. God'],
    [/Neverforgets/gi, 'never forgets'],
    [/HisownIt/gi: 'His own. It'],
    [/Willshow/gi, 'will show'],
    [/Thelevel/gi, 'the level'],
    [/Ofcommitment/gi, 'of commitment'],
    [/Inthethingsof/gi, 'in the things of'],
    [/Godandtowhat/gi: 'God and to what'],
    [/GodvaluesGod/gi: 'God values. God'],
    [/Canpart/gi, 'can part'],
    [/TheRedSea/gi, 'the Red Sea'],
    [/OrJordan/gi, 'or Jordan'],
    [/Oropenthe/gi, 'or open the'],
    [/Eyesof/gi, 'eyes of'],
    [/Theblindthey/gi: 'the blind, they'],
    [/Areunmoved/gi, 'are unmoved'],
    [/Whatwillit/gi, 'What will it'],
    [/TakeforGod/gi, 'take for God'],
    [/Tomoveyou/gi, 'to move you'],
    [/Togetyou/gi, 'to get you'],
    [/TodoGods/gi, "do God's"],
    [/WillWhat/gi: 'will. What'],
    [/Shouldittake/gi, 'should it take'],
    [/Itshould/gi, 'It should'],
    [/Simplytakea/gi, 'simply take a'],
    [/Kingdommindset/gi, 'kingdom mindset'],
    [/Hedoesnt/gi, "He doesn't"],
    [/Needtodo/gi, 'need to do'],
    [/Anythingyou/gi, 'anything, you'],
    [/Simplyneedto/gi, 'simply need to'],
    [/HearHimOrpah/gi: 'hear Him. Orpah'],
    [/Couldnotbemoved/gi, 'could not be moved'],
    [/She stayed/gi, 'She stayed'],
    [/Her groundHer/gi: 'her ground. Her'],
    [/Storyfades/gi, 'story fades'],
    [/Andshe/gi, 'and she'],
    [/DisappearsWe/gi: 'disappears. We'],
    [/Nevergetto/gi, 'never get to'],
    [/Hearabout/gi, 'hear about'],
    [/HeragainUnmoved/gi: 'her again. Unmoved'],
    [/ByGods/gi, "by God's"],
    [/AgendaGodneeds/gi: "agenda. God needs"],
    [/Justtospeak/gi, 'just to speak'],
    [/Ina/gi, 'in a'],
    [/Still small/gi, 'still small'],
    [/VoiceandIwill/gi: 'voice, and I will'],
    [/RespondIdont/gi: 'respond. I don\'t'],
    [/Needthemor/gi, 'need the more'],
    [/Orbeona/gi, 'or be on a'],
    [/BedrestBut/gi: 'bed rest. But'],
    [/Sensitiveenough/gi, 'sensitive enough'],
    [/To simply/gi, 'to simply'],
    [/Hearthestill/gi, 'hear the still'],
    [/SmallvoiceWhat/gi: 'small voice. What'],
    [/Areyou/gi, 'are you'],
    [/Governedbythe/gi, 'governed by the'],
    [/Fleshorthe/gi, 'flesh or the'],
    [/SpiritWhen/gi: 'spirit. When'],
    [/Youaregoverned/gi, 'You are governed'],
    [/Bythekingdom/gi, 'by the kingdom'],
    [/Thememory/gi, 'the memory'],
    [/Of thejust/gi, 'of the just'],
    [/Isblessed/gi, 'is blessed'],
    [/Generationswill/gi, 'Generations will'],
    [/Rememberyou/gi, 'remember you'],
    [/Becauseoftheimpact/gi, 'because of the impact'],
    [/Testimonyand/gi, 'testimony and'],
    [/Legacyyou/gi, 'legacy you'],
    [/LeftWhen/gi: 'left. When'],
    [/Governedbytheworld/gi, 'governed by the world'],
    [/Youareforgotten/gi, 'you are forgotten'],
    [/Whenyou/gi, 'when you'],
    [/Leavethestage/gi, 'leave the stage'],
    [/Ruthisremembered/gi, 'Ruth is remembered'],
    [/Todaynot/gi, 'today, not'],
    [/OrpahBe/gi: 'Orpah. Be'],
    [/Governedby/gi, 'governed by'],
    [/Akingdom/gi, 'a kingdom'],
    [/MindsetDavid/gi: 'mindset. David'],
    [/AndSaul/gi, 'and Saul'],
    [/Thatwas/gi, 'That was'],
    [/Thebeginning/gi, 'the beginning'],
    [/Ofalong/gi, 'of a long'],
    [/Warbetween/gi, 'war between'],
    [/Thosewho/gi, 'those who'],
    [/Wereloyal/gi, 'were loyal'],
    [/ToSauland/gi, 'to Saul and'],
    [/Those loyal/gi, 'those loyal'],
    [/ToDavidAs/gi: 'to David. As'],
    [/Timepassed/gi, 'time passed'],
    [/Davidbecame/gi, 'David became'],
    [/Strongerand/gi, 'stronger and'],
    [/Strongerwhile/gi, 'stronger while'],
    [/Sauls/gi, "Saul's"],
    [/Dynastybecame/gi, 'dynasty became'],
    [/Weakerand/gi, 'weaker and'],
    [/WeakerTheperfect/gi: 'weaker. The perfect'],
    [/Picturedescribing/gi, 'picture describing'],
    [/Those governed/gi, 'those governed'],
    [/Byakingdom/gi, 'by a kingdom'],
    [/Mindsetand/gi, 'mindset and'],
    [/Those governed/gi, 'those governed'],
    [/Bythefleshthechoices/gi: 'by the flesh. The choices'],
    [/Anddecisions/gi, 'and decisions'],
    [/They make/gi, 'they make'],
    [/Telluswho/gi, 'tell us who'],
    [/Isgoverning/gi, 'is governing'],
    [/ThemSaul/gi: 'them. Saul'],
    [/Ischosenbased/gi, 'is chosen based'],
    [/Onhisphysical/gi, 'on his physical'],
    [/Andearthly/gi, 'and earthly'],
    [/CredentialsDavid/gi: 'credentials. David'],
    [/Ischosen/gi, 'is chosen'],
    [/OtherwiseHe/gi: 'otherwise. He'],
    [/Wasthelastborn/gi, 'was the lastborn'],
    [/Youngestand/gi, 'youngest and'],
    [/Notasoldier/gi, 'not a soldier'],
    [/Whenyouare/gi, 'When you are'],
    [/Governedby/gi, 'governed by'],
    [/Akingdom/gi, 'a kingdom'],
    [/Mindsetitsnot/gi: "mindset, it's not"],
    [/Your earthly/gi, 'your earthly'],
    [/Credentialsthat/gi, 'credentials that'],
    [/QualifyyouNoflesh/gi: 'qualify you. No flesh'],
    [/Shallglory/gi, 'shall glory'],
    [/InHispresence/gi, 'in His presence'],
    [/Toserveat/gi, 'To serve at'],
    [/Thetables/gi, 'the tables'],
    [/They appointed/gi, 'they appointed'],
    [/Managementof/gi, 'management of'],
    [/Fooddistribution/gi, 'food distribution'],
    [/Andsobrothers/gi, 'And so, brothers'],
    [/Selectseven/gi, 'select seven'],
    [/Menwhoare/gi, 'men who are'],
    [/Well respected/gi, 'well respected'],
    [/Andarefullof/gi, 'and are full of'],
    [/TheSpirit/gi, 'the Spirit'],
    [/AndwisdomWe/gi: 'and wisdom. We'],
    [/Willgive/gi, 'will give'],
    [/Themthis/gi, 'them this'],
    [/Responsibility/gi, 'responsibility'],
    [/Thereis/gi, 'There is'],
    [/Whatthe/gi, 'what the'],
    [/Kingdomwill/gi, 'kingdom will'],
    [/Lookatand/gi, 'look at, and'],
    [/Whattheworld/gi, 'what the world'],
    [/WilllookatIts/gi: 'will look at. It\'s'],
    [/NotthatGod/gi, 'not that God'],
    [/Doesntwant/gi, "doesn't want"],
    [/Ustohave/gi, 'us to have'],
    [/Earthlycredentials/gi, 'earthly credentials'],
    [/Itsnotthe/gi, "It's not the"],
    [/Basisof/gi, 'basis of'],
    [/His appointing/gi, 'His appointing'],
    [/Thebasis/gi, 'The basis'],
    [/Isgood/gi, 'is good'],
    [/Reputation/gi, 'reputation'],
    [/Reportcharacter/gi: 'report, character'],
    [/Andfullof/gi, 'and full of'],
    [/TheHolyGhost/gi, 'the Holy Ghost'],
    [/AndwisdomYour/gi: 'and wisdom. Your'],
    [/Parametersand/gi, 'parameters and'],
    [/Standardsare/gi, 'standards are'],
    [/DifferentThecriteria/gi: 'different. The criteria'],
    [/Usedtochoose/gi, 'used to choose'],
    [/Davidwasnt/gi, "wasn't"],
    [/Thecriteria/gi, 'the criteria'],
    [/Usedtochoosea/gi, 'used to choose a'],
    [/King in/gi, 'king in'],
    [/TheworldThe/gi: 'the world. The'],
    [/Kingdomcriteria/gi, 'kingdom criteria'],
    [/Andstandard/gi, 'and standard'],
    [/Isdifferentfrom/gi, 'is different from'],
    [/That of/gi, 'that of'],
    [/TheworldThestandards/gi: 'the world. The standards'],
    [/You espouse/gi, 'you espouse'],
    [/Andlift/gi, 'and lift'],
    [/Tellwhat/gi, 'tell what'],
    [/YouvalueGod/gi: 'you value, God'],
    [/Ortheworld/gi, 'or the world'],
    [/Thingsyouput/gi, 'Things you put'],
    [/Higherthan/gi, 'higher than'],
    [/Others/gi, 'others'],
  ];

  // Apply all replacements
  replacements.forEach(([pattern, replacement]) => {
    cleaned = cleaned.replace(pattern, replacement);
  });
  
  // Add proper line breaks before section markers
  cleaned = cleaned.replace(/(TITLE:|Summary|Introduction|Concluding)/gi, '\n\n$1');
  
  // Add line breaks before Bible references
  cleaned = cleaned.replace(/([A-Z][a-z]+ \d+:\d+[A-Z])/g, '\n\n$1');
  
  // Add line breaks before book names
  cleaned = cleaned.replace(/^(Genesis|Exodus|Leviticus|Numbers|Deuteronomy|Joshua|Judges|Ruth|Samuel|Kings|Chronicles|Ezra|Nehemiah|Esther|Job|Psalms|Proverbs|Ecclesiastes|Song|Isaiah|Jeremiah|Lamentations|Ezekiel|Daniel|Hosea|Joel|Amos|Obadiah|Jonah|Micah|Nahum|Habakkuk|Zephaniah|Haggai|Zechariah|Malachi|Matthew|Mark|Luke|John|Acts|Romans|Corinthians|Galatians|Ephesians|Philippians|Colossians|Thessalonians|Timothy|Titus|Philemon|Hebrews|James|Peter|Revelation)/gm, '\n\n$1');
  
  // Clean up excessive line breaks
  cleaned = cleaned.replace(/\n{4,}/g, '\n\n\n');
  
  // Process line by line
  const lines = cleaned.split('\n');
  const processedLines = lines.map(line => line.trim()).filter(line => line.length > 0);
  
  // Rejoin with proper spacing
  cleaned = processedLines.join('\n\n');
  
  // Final cleanup
  cleaned = cleaned.replace(/  +/g, ' ');
  
  return cleaned.trim();
}

// Process all blogs
const cleanedBlogs = blogs.map(blog => ({
  ...blog,
  content: cleanBlogContent(blog.content)
}));

// Write to file
const fs = require('fs');
fs.writeFileSync('./blogs_cleaned.json', JSON.stringify(cleanedBlogs, null, 2));

console.log('Cleaned blogs saved to blogs_cleaned.json');
console.log('\n=== Sample of first blog (first 3000 chars) ===\n');
console.log(cleanedBlogs[0].content.substring(0, 3000));
